
# Project information
site_name: 'Bammellab'
site_description: 'Visualization on the Android Platform'
site_author: 'Jim Andreas'
site_url: 'https://bammellab.github.io/'

# Repository
repo_name: 'bammellab.github.io'
repo_url: 'https://github.com/bammellab/bammellab.github.io'
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2020 Jim Andreas'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs

  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - def_list
  - footnotes
  - meta

# Page tree
nav:
  - Home: 'index.md'
  - Android Apps:
      - 'GamepadTest.md'
  - Videos:
    - Intro: 'YoutubeVideos.md'
    - Video1: 'Video1.md'
    - Video2: 'Video2.md'
  - Uploading: 'Uploading.md'
  - PDB Notes: 'PDBnotes.md'
  - Special Structures: 'Special-Structures.md'


# Notes
#   avoid tabs in vim:
#   :set tabstop=4 shiftwidth=4 expandtab
#
